highlighter: pygments
markdown: rdiscount
github: [Repository metadata]
safe: true
lsi: false
source: .
exclude: [Rakefile, Gemfile, Gemfile.lock, README.md, vendor, serve.sh, LICENSE]
permalink: /:year-:month-:day/:title.html
url: http://timlegrand.github.io
description: Tim Legrand's personal website

default_locale: "en"
authorized_locales: ["en", "fr"]

gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

title: timlegrand
subtitle1_en: High Performance Computing speaker
subtitle2_en: Open Source &amp; Python enthusiast
subtitle1_fr: Expert Calcul Haute Performance
subtitle2_fr: Enthousiaste Open Source &amp; Python
