highlighter: pygments
markdown: rdiscount
github: [Repository metadata]
safe: true
lsi: false
source: .
exclude: [Rakefile, Gemfile, Gemfile.lock, README.md, vendor, serve.sh, LICENSE]
permalink: /:year-:month-:day/:title.html
url: http://timlegrand.github.io
description: Tim Legrand's personal website